name: System Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  System-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Go protobuf plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Generate protobuf code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        protoc --go_out=. --go_opt=paths=source_relative \
               --go-grpc_out=. --go-grpc_opt=paths=source_relative \
               schemas/grpc/kvStoreService.proto

    - name: Install dependencies for kvStore-service
      working-directory: ./kvStore-service
      run: |
        go mod download
        go mod tidy

    - name: Run kvStore-service tests
      working-directory: ./kvStore-service
      run: go test ./test/... -v

    - name: Install dependencies for api-service
      working-directory: ./api-service
      run: |
        go mod download
        go mod tidy

    - name: Run api-service tests
      working-directory: ./api-service
      run: go test ./test/... -v
